project:
  type: book
  # render: false

book:
  favicon: "cric_icon.png"
  title: "An Introduction to Cricket Analytics with R"
  reader-mode: true
  author: "Samrit Pramanik"
  date: "01/25/2025"
  site-url: https://samrit.quarto.pub/carb
  repo-url: https://github.com/samrit2442/cricket-analytics-book-with-r
  chapters:
    - index.qmd
    - warm_up.qmd
    - powerplay.qmd
    - middle_over.qmd
    # - death_over
    # - test_series
    - summary.qmd
    - references.qmd

bibliography: references.bib

# quarto-preview:
#   enabled: false

execute:
  freeze: true

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
  # epub:
  #   cover-image: cover.png
editor: visual

