---
title: Warming Up
subtitle: Data Collection
---

To know the game of cricket, you need to know the history, when and how it was started.

## Data Collection and Sources

There are lot of data sources available online to get started our analysis.

Here, we will mainly focus on the ball-by-ball data so that we can achieve the insights from more granular level.

We will be using open source data from [cricsheet.org](https://cricsheet.org).

## Data Description

The raw data will be downloaded as a zip file. After unzipping we should have multiple .csv files that corresponds to each T20 International matches. There will be another file with same match ids but a suffix "\_info" giving the information of match summary. Our first objective will be to collate all the ball by ball data in a single file or a data frame in R.

We will download the raw data as a zip file, then unzip and save all the files in a directory.

```{r}
#| eval: false
url <- "https://cricsheet.org/downloads/t20s_male_csv2.zip"
download.file(url, dest = "bbb_dataset.zip", mode = "wb")
# unzip("t20s_male_csv2.zip", exdir = dataset_name)
```

Now, we have two sets of data at

1.  '**Ball by Ball**' level.

2.  '**Match**' level.

After unzipping the file, we have a bunch of .csv files with name "1234567.csv" and "1234567_info.csv".

This "\_info.csv" is corresponding to match level data and the other is ball-by-ball.

Next, we will clean up both the datasets separately.
